# ------------- Project

### Create Project
POST localhost:8080/api/projects
Content-Type: application/json

{
  "name": "My Project 1",
  "password": "123"
}

### Login
POST localhost:8080/api/login
Content-Type: application/json

{
  "name": "My Project 1",
  "password": "123"
}

> {%
    client.global.set("auth_token", response.body.token);
  %}

### Refresh
POST localhost:8080/api/refresh
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Get Projects
GET localhost:8080/api/projects

# ------------- Players

### Create Player
POST localhost:8080/api/projects/1/players
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "My Player 1"
}

### Get Players
GET localhost:8080/api/projects/1/players
Authorization: Bearer {{auth_token}}

# ------------- Games

### Create Game
POST localhost:8080/api/projects/1/games
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "My Game 1"
}

### Get Games
GET localhost:8080/api/projects/1/games
Authorization: Bearer {{auth_token}}

###

# ------------- Matches

### Create Match
POST localhost:8080/api/projects/1/games/1/matches
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "teams": [
    {
      "playerIds":[1],
      "score": 3
    },
    {
      "playerIds":[2],
      "score": 5
    }
  ]
}

### Get Matches
GET localhost:8080/api/projects/1/games/1/matches
Authorization: Bearer {{auth_token}}

### Get Player Stats
GET localhost:8080/api/projects/1/games/1/player-stats
Authorization: Bearer {{auth_token}}

###
