# ------------- Project

### Create Project
POST localhost:8080/create-project
Content-Type: application/json

{
  "name": "My Project 2",
  "password": "123"
}

### Select Project
POST localhost:8080/select-project
Content-Type: application/json

{
  "name": "My Project 2",
  "password": "123"
}

> {%
    client.global.set("auth_token", response.body.token);
  %}

### Get Projects
GET localhost:8080/projects

# ------------- Players

### Create Player
POST localhost:8080/project/players
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "My Player 1"
}

### Get Players
GET localhost:8080/project/players
Authorization: Bearer {{auth_token}}

# ------------- Games

### Create Game
POST localhost:8080/project/games
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "My Game 2"
}

### Get Games
GET localhost:8080/project/games
Authorization: Bearer {{auth_token}}

###

# ------------- Matches

### Create Match
POST localhost:8080/project/games/1/matches
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "teams": 2,
  "winningTeam": 2,
  "playerTeamMap": {
    "1": 1,
    "2": 2
  },
  "teamScoreMap": {
    "1": 5,
    "2": 3
  }
}

### Get Matches
GET localhost:8080/project/games/1/matches
Authorization: Bearer {{auth_token}}

### Get Matches by ID
GET localhost:8080/project/games/1/matches/1
Authorization: Bearer {{auth_token}}

###
