version: 2
jobs:
  backend:
    docker:
      - image: circleci/golang:1.13

    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo

      - run: make backend-quality
      - run: make backend

  frontend:
    docker:
      - image: circleci/node:10.16.3

    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "frontend/compelo/package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - frontend/compelo/node_modules
          key: v1-dependencies-{{ checksum "frontend/compelo/package.json" }}

      - run: make frontend-quality
      - run: make frontend

workflows:
  version: 2
  test:
    jobs:
      - frontend
      - backend
