version: 2
jobs:
  backend:
    docker:
      - image: circleci/golang:1.13

    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo

      - run: make backend
      - run: ./go.test.sh
      - run: bash <(curl -s https://codecov.io/bash)

  frontend:
    docker:
      - image: circleci/node:11

    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "frontend/compelo/package.json" }}
            - v1-dependencies-

      - run: make frontend

      - save_cache:
          paths:
            - frontend/compelo/node_modules
          key: v1-dependencies-{{ checksum "frontend/compelo/package.json" }}

workflows:
  version: 2
  test:
    jobs:
      - frontend
      - backend
