name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Set up node 10
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Dependencies
      run: cd frontend/compelo && npm install

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: make build-dev

    - name: Quality
      run: make quality
