name: Build Compelo

on:
  [push, pull_request]

jobs:
  build-compelo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: frontend/compelo/package-lock.json

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'

      - name: Build
        run: make